### ISSUE TITLE
TypeError: Cannot create property 'href' on string

### ISSUE THREAD

**Issue by NfNitLoop** [MikaelPorttila/rss#29]
I just published my first Deno package, <https://deno.land/x/rss2fb@v0.1.0>, and so I started using `rss` to read some more feeds, and then ran into an exception:

```
$ rss2fb
error: Uncaught (in promise) TypeError: Cannot create property 'href' on string '<p><img src="/blog/images/ig-pilates.png" alt="You got this ad because you're a newlywed pilates instructor and you're cartoon crazy. This ad used your location to see you're in La Jolla. You're into parenting blogs and thinking about LGBTQ adoption." /></p>

<p>Companies like Facebook aren’t building technology for you, they’re building technology for your data. They collect everything they can from FB, Instagram, and WhatsApp in order to sell visibility into people and their lives.</p>

<p>This isn’t exactly a secret, but the full picture is hazy to most – dimly concealed within complex, opaquely-rendered systems and fine print designed to be scrolled past. The way most of the internet works today would be considered intolerable if translated into comprehensible real world analogs, but it endures because it is invisible.</p>

<p>'
                        stack[stack.length - 1][attr.name] = attr.value.trim();
                                                          ^
    at SAXParser.parser.onattribute (https://deno.land/x/rss@0.3.6/src/deserializer.ts:96:38)
    at SAXParser.emit (https://deno.land/x/sax_ts@v1.2.10/src/sax.ts:1022:48)
    at SAXParser.emitNode (https://deno.land/x/sax_ts@v1.2.10/src/sax.ts:1223:10)
    at SAXParser.attrib (https://deno.land/x/sax_ts@v1.2.10/src/sax.ts:1132:12)
    at SAXParser.write (https://deno.land/x/sax_ts@v1.2.10/src/sax.ts:888:16)
    at https://deno.land/x/rss@0.3.6/src/deserializer.ts:188:10
    at new Promise (<anonymous>)
    at Module.deserializeFeed (https://deno.land/x/rss@0.3.6/src/deserializer.ts:26:6)
    at syncFeed (https://deno.land/x/rss2fb@v0.1.0/rss2fb.ts:45:32)
    at async main (https://deno.land/x/rss2fb@v0.1.0/rss2fb.ts:28:9)
```

This is while trying to parse a feed like this: <https://deno.land/x/rss2fb@v0.1.0/rss2fb.ts#L45> from <https://signal.org/blog/rss.xml>.

**Comment by MikaelPorttila** [comment]
Hi, thank you for reporting on this issue. 

I ran the XML document that you provided through both XML and RSS validators and noticed that the actual feed is providing invalid documents - they are missing the CDATA element when adding html to the item description field.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsignal.org%2Fblog%2Frss.xml#l216

But I have release a fix where we basically assume that the description field might contain HTML but missing the CData element and so to prevent the underlaying XML parser from throwing this error we'll always convert this field into CDATA.

I'll might do this on all fields which supports CData in future releases if the problem comes up again.

Please try out the new release 0.3.7 and hopefully this should resolve this issue.

**Comment by NfNitLoop** [comment]
Wow! You’re fast! Thanks so much!

I won’t be able to try this out until tomorrow but I’ll let you know.

**Comment by NfNitLoop** [comment]
OK, I no longer get the error, but that blog now gets its summary out from JSONFeed as quoted HTML, instead of raw HTML.

Example:

```typescript
import * as rss from "https://deno.land/x/rss@0.3.7/mod.ts"

async function example(feedURL: string) {
    const response = await fetch(feedURL);
    const xml = await response.text();
    const { feed } = await rss.deserializeFeed(xml, { outputJsonFeed: true });
    console.log("----", feedURL, ":")
    console.log(feed.items[0])
}

await example("https://kotaku.com/rss")
await example("https://signal.org/blog/rss.xml")
```

Output:

```
---- https://kotaku.com/rss :
{
  id: "1847232065",
  summary: '<img src="https://i.kinja-img.com/gawker-media/image/upload/s--bP-OoL90--/c_fit,fl_progressive,q_80,...',
  title: "Indie-Penance Day: A Retrospective",
  external_url: "https://kotaku.com/indie-penance-day-a-retrospective-1847232065",
  content_html: "https://kotaku.com/indie-penance-day-a-retrospective-1847232065",
  author: undefined,
  attachments: undefined,
  url: "https://kotaku.com/indie-penance-day-a-retrospective-1847232065",
  date_published: 2021-07-05T20:15:00.000Z,
  date_modified: 2021-07-05T20:15:00.000Z
}
---- https://signal.org/blog/rss.xml :
{
  id: "https://signal.org/blog/the-instagram-ads-you-will-never-see",
  summary: "&lt;p&gt;&lt;img src=&quot;/blog/images/ig-pilates.png&quot; alt=&quot;You got this ad because you'r...",
  title: "The Instagram ads Facebook won't show you",
  external_url: "https://signal.org/blog/the-instagram-ads-you-will-never-see/",
  content_html: "https://signal.org/blog/the-instagram-ads-you-will-never-see/",
  author: undefined,
  attachments: undefined,
  url: "https://signal.org/blog/the-instagram-ads-you-will-never-see/",
  date_published: 2021-05-04T00:00:00.000Z,
  date_modified: 2021-05-04T00:00:00.000Z
}
```

Note how the `summary` field in the 2nd one has the HTML quoted.

**Comment by MikaelPorttila** [comment]
![image](https://user-images.githubusercontent.com/903468/124520348-7df28c00-ddec-11eb-9b94-aa0de744fa2e.png)

If you inspect the feed you can see that the description field actually contains a mix of both raw and escaped HTML and that's the raw data that you're getting back. You might need to handle these edge cases in your app.

**Comment by NfNitLoop** [comment]
Ohhhh, yeah, I see.  It looks like their feed is just not properly quoting things. Yech.  I'll see if I can find someone on their web team to ping to fix that. I shouldn't work around their bad data.

Thanks!  I think we can close this issue. :)
